api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('offers/status/<int:pk>', views.offer_status),
    path('offers/<int:pk>/comments', views.comments),
    path('offers/<int:pk>/', views.OfferDetailView.as_view()),
    path('offers/', views.offers),
    path('favorite/', views.favorive)
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve
from django.contrib.sitemaps.views import sitemap
from .sitemaps import OfferSitemap


from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
    path('accounts/login/', views.ShaLogin.as_view(), name="login"),
    path('accounts/logout/', views.ShaLogout.as_view(), name='logout'),
    path('profile/delete', views.DeleteUserView.as_view(), name="profile_delete"),
    path('profile/update', views.ChangeProfileView.as_view(), name="profile_change"),
    path('change/<int:pk>/', views.offer_change, name="offer_change"),
    path('delete/<int:pk>/', views.offer_delete, name="offer_delete"),
    path('profile/add/', views.add_new_offer, name="add_new_offer"),
    path('profile/<int:pk>', views.profile_by_id, name="profile_by_id"),
    path('profile/', views.profile, name="profile"),
    path('accounts/password/change', views.ShaPassChangeView.as_view(), name="password_change"),
    path('accounts/password/reset/', views.ShaPassResetView.as_view(), name="password_reset"),
    path('accounts/password/reset/done/', views.ShaPassResetDoneView.as_view(), name="password_reset_done"),
    path('accounts/password/reset/confirm/<str:uidb64>/<str:token>/', views.ShaPassResetConfirmView.as_view(), name="password_reset_confirm"),
    path('accounts/password/reset/complete/', views.ShaPassResetCompleteView.as_view(), name="password_reset_complete"),
    path('accounts/register/activate/<str:sign>/', views.user_activate, name="register_activate"),
    path('accounts/register/done', views.RegisterDone.as_view(), name="register_done"),
    path('accounts/register/', views.RegisterUserView.as_view(), name="register_user"),
    path('accounts/social-auth/', include('social_django.urls', namespace="social")),
    path('reviews/<int:user_id>', views.reviews, name="reviews"),
    path('user_review/<int:offer_pk>/<int:user_pk>/', views.UserReviewView.as_view(), name="user_review"),
    path('<int:category_pk>/<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/', views.by_category, name="by_category"),
    path('chat_list/', views.chat_list, name="chat_list"),
    path('chat/<int:offer_pk>', views.chat, name="chat"),
    path('favorite/', views.favorite, name='favorite'),
    path('services/', views.services, name='services'),
    path('<str:page>/', views.other_page, name="other"),
    path('sitemap.xml', sitemap, {'sitemaps': {'offer': OfferSitemap}}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shabashka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('cookies/', include('cookie_consent.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from django.db.models import Avg

from .utilities import send_activation_notification, get_timestamp_path, send_comment_notification
from .utilities import send_chat_message_notification, send_review_notification


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name="Name")
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name="Order")
    super_category = models.ForeignKey('SuperCategory', on_delete=models.PROTECT, null=True, blank=True,
                                        verbose_name="Super category")
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name="Image")

    def __str__(self):
        super = self.super_category if self.super_category else "Super"
        return f"{super} - {self.name}"

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class SuperCategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_category__isnull=True)


class SuperCategory(Category):
    objects = SuperCategoryManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = "Super category"
        verbose_name_plural = "Super categories"


class SubCategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_category__isnull=False)


class SubCategory(Category):
    objects = SubCategoryManager()

    def __str__(self):
        return f"{self.super_category.name} - {self.name}"

    class Meta:
        proxy = True
        ordering = ('super_category__order', 'super_category__name', 'order', 'name')
        verbose_name = "Subcategory"
        verbose_name_plural = "Subcategories"


class ShaUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name="Activated at")
    send_message = models.BooleanField(default=True, db_index=True, verbose_name="Send messages?")

    average_rating = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True, verbose_name="Average rating")
    favorite = models.ManyToManyField("self", symmetrical=False, blank=True, related_name="followers", verbose_name="Favorites")

    def delete(self, *args, **kwargs):
        for offer in self.offer_set.all():
            offer.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass


user_registrated = Signal('instance')


def user_registrated_dispather(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispather)


class ShaUserAvatar(models.Model):
    user = models.OneToOneField(ShaUser, on_delete=models.CASCADE, related_name="avatar", verbose_name="User",)
    image = models.ImageField(verbose_name="Image")

    def __str__(self):
        return f'{self.user.username} photo - {self.image.url}'

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"


class UserReview(models.Model):
    RATING = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    author = models.ForeignKey(ShaUser, on_delete=models.DO_NOTHING, related_name="review", verbose_name="Author")
    offer = models.ForeignKey("Offer", on_delete=models.DO_NOTHING, related_name="review", verbose_name="Offer")
    reviewal = models.ForeignKey(ShaUser, on_delete=models.CASCADE, related_name="rating", verbose_name="Reviewal")
    speed = models.SmallIntegerField(default=5, choices=RATING,verbose_name="Speed")
    cost = models.SmallIntegerField(default=5, choices=RATING, verbose_name="Cost")
    accuracy = models.SmallIntegerField(default=5, choices=RATING, verbose_name="Accuracy")
    content = models.TextField(verbose_name="Review")
    created = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created")

    def __str__(self):
        return f'Review of {self.author} for {self.reviewal} {self.offer} offer'

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'


def review_save_dispatcher(sender, **kwargs):
    reviewal = kwargs["instance"].reviewal
    user = reviewal.rating.aggregate(rating=(Avg('speed') + Avg('cost') + Avg('accuracy')) / 3)
    reviewal.average_rating = round(user['rating'], 1)
    reviewal.save()
    if kwargs["created"] and reviewal.send_message:
        send_review_notification(kwargs["instance"])


post_save.connect(review_save_dispatcher, sender=UserReview)


class Offer(models.Model):
    STATUS = [
        ('n', 'New'),
        ('a', 'Accepted'),
        ('d', 'Done')
    ]

    category = models.ForeignKey(SubCategory, on_delete=models.PROTECT, verbose_name="Category")
    title = models.CharField(max_length=64, verbose_name="Offer")
    content = models.TextField(verbose_name="Content")
    price = models.FloatField(default=0, verbose_name="Price")
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name="Image")
    author = models.ForeignKey(ShaUser, on_delete=models.CASCADE, verbose_name="Author")
    is_active = models.BooleanField(default=True, db_index=True, verbose_name="Is active")
    created = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created" )
    reviews = models.IntegerField(default=0, verbose_name="Reviews count")
    shared = models.IntegerField(default=0, verbose_name="Share count")
    status = models.CharField(max_length=1, default='n', null=True, blank=True, db_index=True, choices=STATUS, verbose_name="Status")
    winner = models.ForeignKey(ShaUser, on_delete=models.SET_NULL, null=True, blank=True, related_name="accepted_offers" , verbose_name="Executant")

    def delete(self, *args, **kwargs):
        for image in self.additionalimage_set.all():
            image.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/%i/%i/" % (self.category.id, self.id)

    class Meta:
        verbose_name = "Offer"
        verbose_name_plural = "Offers"
        ordering = ["-created"]


class AdditionalImage(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, verbose_name="Offer")
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name="Image")

    class Meta:
        verbose_name = "Additional photo"
        verbose_name_plural = "Additional photos"


class Comment(models.Model):
    MEASUREMENTS = [
                ('h', 'Hour'),
                ('d', 'Day'),
                ('w', 'Week'),
                ('m', 'Month')
               ]

    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, verbose_name="Offer")
    author = models.ForeignKey(ShaUser, on_delete=models.CASCADE, verbose_name="Author")
    content = models.TextField(verbose_name="Content")
    is_active = models.BooleanField(default=True, db_index=True, verbose_name="Is active")
    price = models.FloatField(default=0, null=True, blank=True, verbose_name="Price")
    time_amount = models.SmallIntegerField(default=0, null=True, blank=True, verbose_name="Time amount")
    measure = models.CharField(max_length=1, null=True, blank=True, choices=MEASUREMENTS, verbose_name="Measure")
    created = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created")

    class Meta:
        ordering = ['created']
        verbose_name = "Comment"
        verbose_name_plural = "Comments"


def comment_save_dispatcher(sender, **kwargs):
    author = kwargs['instance'].offer.author
    if kwargs['created'] and author.send_message:
        send_comment_notification(kwargs['instance'])


post_save.connect(comment_save_dispatcher, sender=Comment)


class ChatMessage(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name="chat_messages", verbose_name="Offer")
    author = models.ForeignKey(ShaUser, on_delete=models.CASCADE, related_name="sent_messages", verbose_name="Author")
    receiver = models.ForeignKey(ShaUser, on_delete=models.CASCADE, related_name="received_messages", verbose_name="Receiver")
    content = models.TextField(verbose_name="Message")
    created = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created")

    class Meta:
        ordering = ["-created"]
        verbose_name = "Chat message"
        verbose_name_plural = "Chat messages"


def chat_save_dispatcher(sender, **kwargs):
    receiver = kwargs['instance'].receiver
    if kwargs['created'] and receiver.send_message:
        send_chat_message_notification(kwargs['instance'])


post_save.connect(chat_save_dispatcher, sender=ChatMessage)


class Location(models.Model):
    user = models.OneToOneField(ShaUser, on_delete=models.CASCADE, null=True, blank=True, verbose_name="User", related_name="location")
    offer = models.OneToOneField(Offer, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Offer', related_name="location")
    search_id = models.CharField(max_length=256, verbose_name="Search ID")
    name = models.CharField(max_length=256, verbose_name="Name")

    def __str__(self) -> str:
        return f"{self.name}"

main/templates/main/add_new_offer.html
{% extends 'main/layout.html' %}

{% load static %}
{% load bootstrap4 %}

{% block title %} New offer {% endblock %}

{% block body %}
<div class="container p-5">
    <h2>Add new offer</h2>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' show_label=False%}
    <label for="id_location-0-name">Chose location</label>
    {% bootstrap_formset location layout='horizontal' show_label=False%}
    <datalist id="locations">
    </datalist>

    <h3>Additional photos</h3>
    {% bootstrap_formset formset layout='horizontal' show_label=False%}
    {% buttons submit="Post" %} {% endbuttons %}
    </form>
</div>
<!--<script type="text/javascript" src="{% static 'main/js/location.js' %}"></script>-->
{% endblock %}

main/templates/main/bad_signature.html
{% extends 'main/layout.html' %}

{% block title %} Activation error {% endblock %}

{% block body %}
<h2>User activation</h2>
<p>User was not activated</p>
<p><a href="{% url 'main:register' %}">Register again</a></p>
{% endblock %}

main/templates/main/chat_list.html
{% extends 'main/layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% load custom_tags %}
{% load thumbnail %}

{% block title %} Chat list {% endblock %}

{% block body %}
<div id="page-content" class="sub-page">
<div class="containeer mt-5">
    <center><article>
        <h3 class="center">Chat list</h3>
        
        {% for chat in user_chats %}
        {% ifchanged chat.offer %}
        <div class="p-1"> 
        <div class="chat-mesasge">         
            <div class="row border-bottom-1">
                <div class="chat-head">
                
                <div>{{chat.offer.title}} <span class="small text-muted">{{ chat.created }}</span></div>
                
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 col-sm-2">
                    {% if chat.author.avatar.image %}
                    <img class="border chat-image rounded-circle" src="{% thumbnail chat.author.avatar.image 'default' %}" alt="">
                    {% else %}
                    <img class="border chat-image rounded-circle" style="background-color: #777;" src="{% static 'main/images/profile-ph.png' %}" alt="">
                    {% endif %}
                </div>
                <div class="col-md-10 col-sm-10">
                    <a href="{% url 'main:chat' offer_pk=chat.offer.pk %}">
                    <span class="">{{ chat.content }}</span>
                    </a>
                </div>
                 
            </div>                
        </div>
    </div>        
        {% endifchanged %}
        {% endfor %}
        
    </article></center>
</div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load custom_tags %}



{% block  title %} Main page {% endblock %}

{% block body %}

<header>
	<div class="logo">
	  <a href="{% url 'main:index' %}"><img src="{% static 'main/images/logo.png' %}"></a>
	</div>
  </header>	
    
	<div id="page-content" class="index-page">
		<div id="container">
	{% for offer in offers %}
			{% include "main/offer_template.html" %}
	
	{% endfor %}
	</div>  
		<div class="d-flex justify-content-center">
			{% bootstrap_pagination page url=keyword %}    
		</div>   
	</div>
	
{% endblock %}	

main/templates/main/logout.html
{% extends 'main/layout.html' %}

{% block title %}Logout{% endblock %}

{% block body %}
<div class="container center">
<h2>Logout</h2>
<p>We will miss you</p>
</div>
{% endblock %}

main/templates/main/offer_template.html
{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load custom_tags %}


<div class="item">
				<div class="content-item">
					{% url 'main:detail' category_pk=offer.category.pk pk=offer.pk as url %}
					<a href="{% url 'main:by_category' pk=offer.category.pk %}" class="btn btn-small btn-{{offer.category.super_category.order}}">{{offer.category.name}}</a>
					<div class="time"> {{offer.created}}</div>
					<h3 class="title-item"><a href="{{url}}{{all}}">{{offer.title}}</a></h3>
					<p class="info">{% limit_text offer.content %}</p>
					<ul class="list-inline">
						<li class="list-inline-item"><i class="fa fa-eye"></i> {{ offer.reviews }} </li>
						<li class="list-inline-item"><i class="fa fa-comment"></i> {{offer.comment_set.count}}</li>
						<li class="list-inline-item"><i class="fa fa-heart
							{% if user|in_followers:offer.author %}
							liked
							{% endif %}
							"></i>
							{{ offer.author.followers.count }} </li>
						<li class="list-inline-item"><i class="fa fa-share"></i> {{offer.shared}}</li>
					</ul>
				</div>
				<div class="bottom-item">
					<a href="#" class="btn btn-share share"><i class="fa fa-share-alt"></i> </a>
					<span class="mx-3"><span class="uah">&#36</span> {{offer.price}}</span>
<!--					<span class="user f-right">-->
<!--						<a href="{% url 'main:profile_by_id' pk=offer.author.pk %}">-->
<!--							{% if offer.author.first_name and offer.author.last_name %}-->
<!--							{{offer.author.first_name}} {{offer.author.last_name}}-->
<!--							{% else %}-->
<!--							{{offer.author}}-->
<!--							{% endif %}-->
<!--						</a>-->
<!--						{% if offer.author.avatar.image %}-->
<!--						<img class="border profile-img rounded-circle" src="{% thumbnail offer.author.avatar.image 'default' %}" alt="">-->
<!--						{% else %}-->
<!--						<img class="border profile-img rounded-circle" style="background-color: #777;" src="{% static 'main/images/profile-ph.png' %}" alt="">-->
<!--						{% endif %}-->
<!--					</span>-->
				</div>
			</div>

main/templates/main/profile.html
{% extends 'main/layout.html' %}
{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load custom_tags %}


{% block title %} Profile {% endblock %}

{% block body %}
{% if user == request.user %}
<div id="avatarModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Change avatar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>        
        <div class="modal-body center">
            <form method="POST" enctype="multipart/form-data">    
                <div>
                    {% if user.avatar.image %}
                    <img class="border profile-img" src="{{user.avatar.image.url}}" alt="">
                    {% else %}
                    <img class="border profile-img" style="background-color: #777;" src="{% static 'main/images/profile-ph.png' %}" alt="">
                    {% endif %}
                </div>
                {% csrf_token %}
                {% bootstrap_form avatar_form alert_error_type='all' %}
                {% bootstrap_form_errors avatar_form %}
            </form>
                
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
      </div>
    </div>
</div>

{% endif %}
<div class="container py-5">
    {% if user == request.user %}
    {% if not user.first_name or not user.last_name or not user.location or not user.avatar%}
    <div class="alert alert-warning" role="alert">    
        <ul>
        {% if user == request.user and not user.first_name or not user.last_name%}
            <li>Fill up your profile.</li>
        {% endif %}

        {% if not user.first_name or not user.last_name %}
            <li>We do not recommend our users to trust people with an incomplete profile.</li>
        {% endif %}

        {% if not user.avatar %}
            <li>Adding a current photo to your profile increases trust.</li>
        {% endif %}

        {% if user == request.user and not user.location %}
            <li>Kindly enter your city to ensure a more efficient search for offers.</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
    {% endif %}

    <div class="row">
        <div class="col-lg-3">
            {% if user.avatar.image %}
            <img class="border profile-img"  src="{{user.avatar.image.url}}" alt="">
            {% else %}
            <img class="border profile-img" style="background-color: #777;" src="{% static 'main/images/profile-ph.png' %}" alt="">
            {% endif %}
        </div>
        <div class="col-lg-9">            
            <h3>{{ user.username }} profile</h3>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-6">           
                    <div><b> Name:</b>
                        {% if user.first_name and user.last_name %}
                            {{user.first_name}} {{user.last_name}}
                        {% else %} 
                            Wasn't provided
                        {% endif %}
                    </div>
                    <div><b>City:</b> {% if user.location %} {{user.location}} {% else %} Undefined{% endif %}</div>
                    <div><b>Score:</b>
                        {% if reviews %}
                        {% show_rating user.average_rating %}
                        {% else %}
                        <i class="fa fa-star" style="color: #ddad10;"></i>
                        <i class="fa fa-star" style="color: #ddad10;"></i>
                        <i class="fa fa-star" style="color: #ddad10;"></i>
                        <i class="fa fa-star" style="color: #ddad10;"></i>
                        <i class="fa fa-star" style="color: #ddad10;"></i>
                        {% endif %}
                        <a href="{% url 'main:reviews' user_id=user.id %}">(reviews - {{reviews|default_if_none:"0"}})</a>
                    </div>            
                    <div><b>Successfully finished: </b>{{reviews|default_if_none:"0"}}</div>
                                               
                </div>
                
                <div class="col-lg-4 col-md-4 col-sm 6">
                {% if user == request.user %}    
                    <div><a href="#avatarModal" class="mx-1" data-toggle="modal" data-target="#avatarModal"><i class="fa fa-user"></i> Change profile picture </a></div>
                    <div><a href="{% url 'main:profile_change' %}" class="mx-1"><i class="fa fa-pencil"></i> Edit profile </a></div>
                    <div><a href="{% url 'main:password_change' %}" class="mx-1"><i class="fa fa-lock"></i> Change password </a></div>
                    <div><a href="{% url 'main:profile_delete' %}" class="mx-1"><i class="fa fa-close"></i> Delete profile </a></div>
                {% else %}
                {% if request.user|in_followers:user %}                                
                    <a href="#" id="favorite" data-user="{{ user.id }}"><i class="fa fa-user"></i> Add to favorites</a>
                {% else %}
                    <a href="#" id="favorite" data-user="{{ user.id }}"><i class="fa fa-user-plus"></i> Remove from favorites </a>
                {% endif %}	
                {% endif %}
                </div>
            </div>
        </div>
    </div>


<hr>
<div id="page-content" class="index-page">
    <div id="container">
        {% for offer in offers %}
        <div class="item">            
            <div class="content-item">
                {% url 'main:detail' category_pk=offer.category.pk pk=offer.pk as url %}
                <a href="{% url 'main:by_category' pk=offer.category.pk %}" class="btn btn-small btn-{{offer.category.super_category.order}}">{{offer.category.name}}</a>
                <div class="time"> {{offer.created}}</div>
                <h3 class="title-item"><a href="{{url}}{{all}}">{{offer.title}}</a></h3>
                <p class="info">{% limit_text offer.content %}</p>
                <ul class="list-inline">            
                    <li class="list-inline-item"><i class="fa fa-eye"></i> {{ offer.reviews }} </li>
                    <li class="list-inline-item"><i class="fa fa-comment"></i> {{offer.comment_set.count}}</li>
                    <li class="list-inline-item"><i class="fa fa-heart 
                        {% if request.user|in_followers:user %}
                        liked
                        {% endif %}							
                        "></i> 
                        {{ offer.author.followers.count }} </li>
                    <li class="list-inline-item"><i class="fa fa-share"></i> {{offer.shared}}</li>
                </ul>
            </div>
            <div class="bottom-item">
                <a href="#" class="btn btn-share share"><i class="fa fa-share-alt"></i> </a>
                <span class="mx-3"><span class="uah">&#8372</span> {{offer.price}}</span>
                <span class="user f-right">Posted
                    <a href="{% url 'main:profile_by_id' pk=offer.author.pk %}">
                        {% if offer.author.first_name and offer.author.last_name %}
                        {{offer.author.first_name}} {{offer.author.last_name}}
                        {% else %}
                        {{offer.author}}
                        {% endif %}
                    </a>
                    {% if user.avatar.image %}
                    <img class="border profile-img rounded-circle" src="{% thumbnail user.avatar.image 'default' %}" alt="">
                    {% else %}
                    <img class="border profile-img rounded-circle" style="background-color: #777;" src="{% static 'main/images/profile-ph.png' %}" alt="">
                    {% endif %}
                    
                </span>
            </div>
        </div>


        {% endfor %}
    </div>
</div>
</div>

{% endblock %}

main/templates/main/register_user.html
{% extends 'main/layout.html' %}
{% load bootstrap4 %}
{% load static %}
{% load crispy_forms_tags %} 

{% block title %} Sign up {% endblock %}


{% block body %}
<header>
	<div class="logo">
	  <a href="index.html"><img src="{% static 'main/images/logo.png' %}"></a>
	</div>
</header>

{% if user.is_authenticated %}
<p> You are already logged in</p>
{% else %}  
<!-- Modal HTML -->
<div id="registerModal" class="modal fade signup-modal">
	<div class="modal-dialog modal-login">
		<div class="modal-content">
			<div class="modal-header">
				<div class="avatar">
					<img src="{% static 'main/images/profile-ph.png' %}" alt="Avatar">
				</div>				
				<h4 class="modal-title">Sing Up</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			</div>
			<div class="modal-body si">
				<form id="registrationForm" action="/accounts/register/" method="post">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{next}}">				
					{% crispy form %}					
				</form>
			</div>
			<div class="modal-footer">
				<p class="small text-center">By clicking the Sign Up button, you agree to our <br><a href="#">Terms &amp; Conditions</a>, and <a href="#">Privacy Policy</a>.</p>
				
			</div>
			<div class="text-center">Already have an account? <a href="{% url 'main:login' %}" >Login</a>.</div>
		</div>
	</div>
</div>    
<div class="container">
   
        <center><article class="py-5 center">                  
			<h1>We are happy to welcome you!</h1>
			<a href="{% url 'main:login' %}" class="loginShow mx-2">Login</a> <a href="#" class="registerShow mx-2">Sign up</a>
    	</article> </center> 
    
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        $("#registerModal").modal("show");
        
        $(".registerShow").click(function(){                
            $("#registerModal").modal("show");
            return false;
        })
    })
</script>
{% endif %}
{% endblock %}

main/templates/main/user_is activated.html
{% extends 'main/layout.html' %}

{% block title %} Successfully activated {% endblock %}

{% block body %}
<h2>User activation</h2>
<p>A user with this name was already activated.</p>
<p><a href="{% url 'main:login' %}">Login</a></p>
{% endblock %}